//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMatrixData", ReplyAction="http://tempuri.org/IService1/GetMatrixDataResponse")]
        WCF_TRSPO_Lib.ObjectObgortka GetMatrixData(int n, WCF_TRSPO_Lib.MatrixEnum Letter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMatrixData", ReplyAction="http://tempuri.org/IService1/GetMatrixDataResponse")]
        System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> GetMatrixDataAsync(int n, WCF_TRSPO_Lib.MatrixEnum Letter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVectorData", ReplyAction="http://tempuri.org/IService1/GetVectorDataResponse")]
        WCF_TRSPO_Lib.ObjectObgortka GetVectorData(int n, WCF_TRSPO_Lib.VectorEnum Letter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetVectorData", ReplyAction="http://tempuri.org/IService1/GetVectorDataResponse")]
        System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> GetVectorDataAsync(int n, WCF_TRSPO_Lib.VectorEnum Letter);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CompileY1", ReplyAction="http://tempuri.org/IService1/CompileY1Response")]
        WCF_TRSPO_Lib.ObjectObgortka CompileY1(MathNet.Numerics.LinearAlgebra.Vector<double> vectorB, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CompileY1", ReplyAction="http://tempuri.org/IService1/CompileY1Response")]
        System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> CompileY1Async(MathNet.Numerics.LinearAlgebra.Vector<double> vectorB, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CompileY2", ReplyAction="http://tempuri.org/IService1/CompileY2Response")]
        WCF_TRSPO_Lib.ObjectObgortka CompileY2(MathNet.Numerics.LinearAlgebra.Vector<double> vectorC1, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA1, MathNet.Numerics.LinearAlgebra.Vector<double> vectorB1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CompileY2", ReplyAction="http://tempuri.org/IService1/CompileY2Response")]
        System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> CompileY2Async(MathNet.Numerics.LinearAlgebra.Vector<double> vectorC1, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA1, MathNet.Numerics.LinearAlgebra.Vector<double> vectorB1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CompileY3", ReplyAction="http://tempuri.org/IService1/CompileY3Response")]
        WCF_TRSPO_Lib.ObjectObgortka CompileY3(MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA2, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixB2, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixC2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CompileY3", ReplyAction="http://tempuri.org/IService1/CompileY3Response")]
        System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> CompileY3Async(MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA2, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixB2, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixC2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MainThreadCalculating", ReplyAction="http://tempuri.org/IService1/MainThreadCalculatingResponse")]
        WCF_TRSPO_Lib.ObjectObgortka MainThreadCalculating(int n, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixY3, MathNet.Numerics.LinearAlgebra.Vector<double> vectorY2, MathNet.Numerics.LinearAlgebra.Vector<double> vectorY1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MainThreadCalculating", ReplyAction="http://tempuri.org/IService1/MainThreadCalculatingResponse")]
        System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> MainThreadCalculatingAsync(int n, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixY3, MathNet.Numerics.LinearAlgebra.Vector<double> vectorY2, MathNet.Numerics.LinearAlgebra.Vector<double> vectorY1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.ServiceReference1.IService1>, Client.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_TRSPO_Lib.ObjectObgortka GetMatrixData(int n, WCF_TRSPO_Lib.MatrixEnum Letter) {
            return base.Channel.GetMatrixData(n, Letter);
        }
        
        public System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> GetMatrixDataAsync(int n, WCF_TRSPO_Lib.MatrixEnum Letter) {
            return base.Channel.GetMatrixDataAsync(n, Letter);
        }
        
        public WCF_TRSPO_Lib.ObjectObgortka GetVectorData(int n, WCF_TRSPO_Lib.VectorEnum Letter) {
            return base.Channel.GetVectorData(n, Letter);
        }
        
        public System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> GetVectorDataAsync(int n, WCF_TRSPO_Lib.VectorEnum Letter) {
            return base.Channel.GetVectorDataAsync(n, Letter);
        }
        
        public WCF_TRSPO_Lib.ObjectObgortka CompileY1(MathNet.Numerics.LinearAlgebra.Vector<double> vectorB, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA) {
            return base.Channel.CompileY1(vectorB, matrixA);
        }
        
        public System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> CompileY1Async(MathNet.Numerics.LinearAlgebra.Vector<double> vectorB, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA) {
            return base.Channel.CompileY1Async(vectorB, matrixA);
        }
        
        public WCF_TRSPO_Lib.ObjectObgortka CompileY2(MathNet.Numerics.LinearAlgebra.Vector<double> vectorC1, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA1, MathNet.Numerics.LinearAlgebra.Vector<double> vectorB1) {
            return base.Channel.CompileY2(vectorC1, matrixA1, vectorB1);
        }
        
        public System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> CompileY2Async(MathNet.Numerics.LinearAlgebra.Vector<double> vectorC1, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA1, MathNet.Numerics.LinearAlgebra.Vector<double> vectorB1) {
            return base.Channel.CompileY2Async(vectorC1, matrixA1, vectorB1);
        }
        
        public WCF_TRSPO_Lib.ObjectObgortka CompileY3(MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA2, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixB2, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixC2) {
            return base.Channel.CompileY3(matrixA2, matrixB2, matrixC2);
        }
        
        public System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> CompileY3Async(MathNet.Numerics.LinearAlgebra.Matrix<double> matrixA2, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixB2, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixC2) {
            return base.Channel.CompileY3Async(matrixA2, matrixB2, matrixC2);
        }
        
        public WCF_TRSPO_Lib.ObjectObgortka MainThreadCalculating(int n, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixY3, MathNet.Numerics.LinearAlgebra.Vector<double> vectorY2, MathNet.Numerics.LinearAlgebra.Vector<double> vectorY1) {
            return base.Channel.MainThreadCalculating(n, matrixY3, vectorY2, vectorY1);
        }
        
        public System.Threading.Tasks.Task<WCF_TRSPO_Lib.ObjectObgortka> MainThreadCalculatingAsync(int n, MathNet.Numerics.LinearAlgebra.Matrix<double> matrixY3, MathNet.Numerics.LinearAlgebra.Vector<double> vectorY2, MathNet.Numerics.LinearAlgebra.Vector<double> vectorY1) {
            return base.Channel.MainThreadCalculatingAsync(n, matrixY3, vectorY2, vectorY1);
        }
    }
}
